CREATE DATABASE Turmas_Professor;
USE Turmas_Professor;

CREATE TABLE usuario (
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
usuario VARCHAR(60) NOT NULL,
email VARCHAR(120) NOT NULL,
senha TEXT NOT NULL,
PRIMARY KEY (id)
)ENGINE = INNODB;

CREATE TABLE professor(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
nome VARCHAR(120) NOT NULL,
email VARCHAR(120) NOT NULL,
telefone CHAR(14) NOT NULL,
PRIMARY KEY(id)
)ENGINE = INNODB;

CREATE TABLE turma(
id INT UNSIGNED AUTO_INCREMENT NOT NULL,
nome VARCHAR(80) NOT NULL,
id_professor INT UNSIGNED NOT NULL,
PRIMARY KEY(id),
FOREIGN KEY (id_professor) REFERENCES professor(id)
)ENGINE = INNODB; 